"""alembic/versions/0001_initial_schema.py — Initial tables"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB

revision  = "0001"
down_revision = None
branch_labels = None
depends_on    = None


def upgrade():
    # All tables are created by SQLAlchemy Base.metadata.create_all()
    # in db/connection.py on first startup (dev mode).
    # This migration is a no-op placeholder for production Alembic workflow.
    # TODO DB-04: generate proper autogenerated migration:
    #   alembic revision --autogenerate -m "initial schema"
    pass


def downgrade():
    pass
