"""add updated_at to zones

Revision ID: 1c5dc0706bdb
Revises: e86a5f3b67d4
Create Date: 2026-03-15 16:26:15.140185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5dc0706bdb'
down_revision: Union[str, Sequence[str], None] = 'e86a5f3b67d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'updated_at')
    # ### end Alembic commands ###
