"""initial migration

Revision ID: 7a29e046a79a
Revises: f5457ad07408
Create Date: 2026-03-07 14:02:20.660862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a29e046a79a'
down_revision: Union[str, Sequence[str], None] = 'd1add19ad75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_configs',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('zones',
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('polygon_coords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('zone_type', sa.String(), nullable=True),
    sa.Column('dwell_threshold_sec', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('cameras',
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rtsp_url', sa.String(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('camera_id')
    )
    op.create_table('rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('incidents',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('zone_name', sa.String(), nullable=True),
    sa.Column('object_class', sa.String(), nullable=True),
    sa.Column('threat_level', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_table('segments',
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('minio_path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('has_motion', sa.Boolean(), nullable=True),
    sa.Column('has_detections', sa.Boolean(), nullable=True),
    sa.Column('detection_count', sa.Integer(), nullable=True),
    sa.Column('retain_until', sa.DateTime(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_index('ix_segments_camera_start', 'segments', ['camera_id', 'start_time'], unique=False)
    op.create_index('ix_segments_start', 'segments', ['start_time'], unique=False)
    op.create_index(op.f('ix_segments_start_time'), 'segments', ['start_time'], unique=False)
    op.create_table('detections',
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('object_class', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('zone_name', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('dwell_sec', sa.Float(), nullable=True),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('bbox_x2', sa.Float(), nullable=True),
    sa.Column('bbox_y2', sa.Float(), nullable=True),
    sa.Column('frame_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('is_threat', sa.Boolean(), nullable=True),
    sa.Column('threat_level', sa.String(), nullable=True),
    sa.Column('vlm_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.segment_id'], ),
    sa.PrimaryKeyConstraint('detection_id')
    )
    op.create_index('ix_detections_camera_ts', 'detections', ['camera_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_detections_event_id'), 'detections', ['event_id'], unique=False)
    op.create_index('ix_detections_incident', 'detections', ['incident_id'], unique=False)
    op.create_index('ix_detections_segment', 'detections', ['segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detections_segment', table_name='detections')
    op.drop_index('ix_detections_incident', table_name='detections')
    op.drop_index(op.f('ix_detections_event_id'), table_name='detections')
    op.drop_index('ix_detections_camera_ts', table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_segments_start_time'), table_name='segments')
    op.drop_index('ix_segments_start', table_name='segments')
    op.drop_index('ix_segments_camera_start', table_name='segments')
    op.drop_table('segments')
    op.drop_table('incidents')
    op.drop_table('rules')
    op.drop_table('cameras')
    op.drop_table('zones')
    op.drop_table('rag_configs')
    op.drop_table('notification_rules')
    # ### end Alembic commands ###
