"""your change

Revision ID: bdedd7b8c86e
Revises: 820eaa05584c
Create Date: 2026-03-08 19:58:20.609059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'bdedd7b8c86e'
down_revision: Union[str, Sequence[str], None] = '820eaa05584c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = '7a29e046a79a'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('user_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_accounts_username'), 'user_accounts', ['username'], unique=True)
    op.add_column('detections', sa.Column('vlm_embedding', Vector(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'vlm_embedding')
    op.drop_index(op.f('ix_user_accounts_username'), table_name='user_accounts')
    op.drop_table('user_accounts')
    # ### end Alembic commands ###
