[alembic]
script_location = alembic
sqlalchemy.url = postgresql://doadmin:AVNS_A3wDakBED6KTQ56zQHH@hukkanawa-dala-do-user-20573204-0.h.db.ondigitalocean.com:25060/argus_test?sslmode=require

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
